import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Box } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "ERP Landing Page",
  description: "Generated by Toru",
  viewport: "width=device-width, initial-scale=1",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <Box className="flex flex-col justify-between">
            <Header />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </Box>
        </Providers>
      </body>
    </html>
  )
}